name: Build and deploy to AKS

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - name: Find and Replace deployment manifest
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "PLACEHOLDER_IMAGE_LOCATION"
          replace:  xrouterserviceexplorer/servicenode.api:${{ github.sha }}
          include: "./Servicenode.Api/deployment.yml" 
          
        
      - run: echo xrouterserviceexplorer/servicenode.api:${{ github.sha }}
      - run: cat ./Servicenode.Api/deployment.yml
        
